---

- name: "6.2.2.2 | PATCH | Ensure journald ForwardToSyslog is disabled"
  when: rhel10cis_rule_6_2_2_2
  tags:
    - level1-server
    - level2-workstation
    - patch
    - journald
    - rule_6.2.2.2
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-6
    - NIST800-53R5_AU-7
    - NIST800-53R5_AU-12
  notify: Restart journald
  block:
    - name: "6.2.2.2 | PATCH | Ensure journald ForwardToSyslog is disabled | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/forwardtosyslog.conf.j2
        dest: "/etc/systemd/journald.conf.d/{{ rhel10cis_journald_forwardsyslog }}"
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'

    - name: "6.2.2.2 | PATCH | Ensure journald ForwardToSyslog is disabled | comment out current entries"
      when:
        - prelim_journald_conf_files.files is defined
        - prelim_journald_conf_files.matched > 0
        - "rhel10cis_journald_forwardsyslog not in item.path"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: (?i)^(\s*ForwardToSyslog)
        replace: "#\\1"
      loop: "{{ prelim_journald_conf_files.files }}"

- name: "6.2.2.3 | PATCH | Ensure journald Compress is configured"
  when: rhel10cis_rule_6_2_2_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - journald
    - rule_6.2.2.3
    - NIST800-53R5_AU-4
  notify: Restart journald
  block:
    - name: "6.2.2.3 | PATCH | Ensure journald Compress is configured | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/storage.conf.j2 # Added to the same file as 6.2.2.4
        dest: "/etc/systemd/journald.conf.d/{{ rhel10cis_journald_storage }}"
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'

    - name: "6.2.2.3 | PATCH | Ensure journald Compress is configured | comment out current entries"
      when:
        - prelim_journald_conf_files.files is defined
        - prelim_journald_conf_files.matched > 0
        - "rhel10cis_journald_storage not in item.path"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: (?i)^(\s*compress=)
        replace: "#\\1"
      loop: "{{ prelim_journald_conf_files.files }}"

- name: "6.2.2.4 | PATCH | Ensure journald Storage is configured"
  when: rhel10cis_rule_6_2_2_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - journald
    - rule_6.2.2.4
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-12
  notify: Restart journald
  block:
    - name: "6.2.2.4 | PATCH | Ensure journald Storage is configured | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/storage.conf.j2
        dest: "/etc/systemd/journald.conf.d/{{ rhel10cis_journald_storage }}"
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'

    - name: "6.2.2.4 | PATCH | Ensure journald Storage is configured | comment out current entries"
      when:
        - prelim_journald_conf_files.files is defined
        - prelim_journald_conf_files.matched > 0
        - "rhel10cis_journald_storage not in item.path"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: (?i)^(\s*storage=)
        replace: "#\\1"
      loop: "{{ prelim_journald_conf_files.files }}"
